import Head from "next/head";
import { Chat } from "$/components/chat";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat Streaming</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-neutral-900">
        <Chat />
      </main>
    </>
  );
}
